name: innovation
description: A new Flutter project.
publish_to: "none" # flutter pub publish

# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# flutter pub upgrade --major-versions
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  package_info_plus: ^1.4.3
  auto_route: ^4.2.0
  build_runner: ^2.1.11
  provider: ^6.0.3
  responsive_builder: ^0.4.2
  swipeable_page_route: ^0.2.6
  google_fonts: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  decorated_icon: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.0

flutter:
  uses-material-design: true

  # https://flutter.dev/assets-and-images/#resolution-aware
  # https://flutter.dev/assets-and-images/#from-packages
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # https://flutter.dev/custom-fonts/#from-packages
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
